---
title: "PRISM ic50 - klaeger - LINCS classification models"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(tictoc)
library(doParallel)
library(patchwork)
library(ROCR)

knitr::opts_knit$set(root.dir = here())
```

```{r}
#read in data 
compound_match_list = read_csv(here('results/LINCS_PRISM_klaeger_combined_drug_matches_final.csv'))

LINCS_klaeger_data_long = read_csv(here('results/all_klaeger_LINCS_data_for_ml_long.csv'))

PRISM_ic50 = read_csv(here('results/PRISM_ic50_for_ml.csv'))

CCLE = read_rds(here('data/full_CCLE_expression_set_for_ML.rds')) %>% 
	rename('depmap_id' = DepMap_ID) %>% 
	filter(depmap_id %in% PRISM_ic50$depmap_id)

```

```{r}

# CCLE_binary = CCLE %>% 
# 	pivot_longer(-depmap_id, names_to = 'gene', values_to = 'TPM') %>% 
# 	mutate(TPM_binary = if_else(
# 		TPM > 0,
# 		1,
# 		0
# 	)) %>% 
# 	select(-TPM) %>% 
# 	pivot_wider(names_from = gene, values_from = TPM_binary)

PRISM_ic50_binarized = PRISM_ic50 %>% 
	mutate(ic50_binary = if_else(
		ic50 <= median(PRISM_ic50$ic50),
		1,
		0
	))

LINCS_klaeger_data_for_model = LINCS_klaeger_data_long %>% 
	mutate(act_gene_name = paste0('act_', kinase)) %>% 
	select(-kinase, -binary_hit) %>% 
	left_join(compound_match_list,
		by = c('drug' = 'klaeger_name')
	) %>% 
	select(-LINCS_name) %>% 
	rename('PRISM_name_klaeger' = PRISM_name, 'broad_id_klaeger' = broad_id) %>%
	left_join(compound_match_list,
		by = c('drug' = 'LINCS_name')
	) %>% 
	select(-klaeger_name) %>% 
	rename('PRISM_name_LINCS' = PRISM_name, 'broad_id_LINCS' = broad_id) %>% 
	mutate(
		PRISM_name = if_else(
		is.na(PRISM_name_klaeger),
		PRISM_name_LINCS,
		PRISM_name_klaeger
		),
		broad_id = if_else(
			is.na(broad_id_klaeger),
			broad_id_LINCS,
			broad_id_klaeger
		)
	) %>% 
	select(-PRISM_name_klaeger, -broad_id_klaeger, -PRISM_name_LINCS, -broad_id_LINCS) %>% 
	filter(!is.na(broad_id)) %>% 
	unique() %>% 
	pivot_wider(names_from = act_gene_name, values_from = relative_intensity) %>% 
	mutate_all(~replace(., is.na(.), 1))

all_model_data = PRISM_ic50_binarized %>% 
	left_join(CCLE, by = 'depmap_id') %>% 
	left_join(LINCS_klaeger_data_for_model, by = c('broad_id')) %>% 
	select(-name, -PRISM_name) %>%
	mutate(ic50_binary = as.factor(ic50_binary)) %>% 
	drop_na()

LINCS_klaeger_data_for_model_binary_hit = LINCS_klaeger_data_long %>% 
	mutate(act_gene_name = paste0('act_', kinase)) %>% 
	select(-kinase, -relative_intensity) %>% 
		left_join(compound_match_list,
		by = c('drug' = 'klaeger_name')
	) %>% 
	select(-LINCS_name) %>% 
	rename('PRISM_name_klaeger' = PRISM_name, 'broad_id_klaeger' = broad_id) %>%
	left_join(compound_match_list,
		by = c('drug' = 'LINCS_name')
	) %>% 
	select(-klaeger_name) %>% 
	rename('PRISM_name_LINCS' = PRISM_name, 'broad_id_LINCS' = broad_id) %>% 
	mutate(
		PRISM_name = if_else(
		is.na(PRISM_name_klaeger),
		PRISM_name_LINCS,
		PRISM_name_klaeger
		),
		broad_id = if_else(
			is.na(broad_id_klaeger),
			broad_id_LINCS,
			broad_id_klaeger
		)
	) %>% 
	select(-PRISM_name_klaeger, -broad_id_klaeger, -PRISM_name_LINCS, -broad_id_LINCS) %>% 
	filter(!is.na(broad_id)) %>% 
	unique() %>%
	pivot_wider(names_from = act_gene_name, values_from = binary_hit) %>% 
	mutate_all(~replace(., is.na(.), 0))

all_binary_model_data = PRISM_ic50_binarized %>% 
	left_join(CCLE, by = 'depmap_id') %>% 
	left_join(LINCS_klaeger_data_for_model_binary_hit, by = c('broad_id')) %>% 
	select(-name, -PRISM_name) %>% 
	drop_na()
	

```

```{r}
# binary feature selection

binary_data = all_binary_model_data %>% 
	mutate(across(starts_with(c('act','ic50_binary')), ~ as.factor(.)))

write_rds(binary_data, here('results/all_model_binary_data.rds'))

# all_binary_model_data_long = all_binary_model_data %>% 
# 	pivot_longer(c(-drug, -broad_id, -depmap_id, -ccle_name, -ic50_binary), names_to = 'feature', values_to = 'value')
# 
# feature_variances = all_binary_model_data_long %>% 
# 	select(feature, value) %>% 
# 	group_by(feature) %>% 
# 	summarise(var = var(value))
# 
# features_to_select = feature_variances %>% 
# 	filter(var > 0)
# write_csv(features_to_select, here('results/binary_data_variable_features.csv'))

# data_for_feature_selection = all_binary_model_data %>% 
# 	select(ic50_binary, any_of(features_to_select$feature))
# 
# feature_set = all_binary_model_data %>% 
# 	select(any_of(features_to_select$feature))
# 
# roc_vals = data.frame()
# i = 2
# for(i in 1:dim(feature_set)[2]) {
# 	this_feature = names(feature_set)[i]
# 	this_feature_data = all_binary_model_data %>% 
# 		select(any_of(this_feature))
# 	this_feature_pred = prediction(all_binary_model_data$ic50_binary, this_feature_data[1])
# 	this_feature_perf_auc = performance(this_feature_pred, measure = 'auc')
# 	this_feature_perf_aucpr = performance(this_feature_pred, measure = 'aucpr')
# 	roc_vals = bind_rows(
# 			roc_vals,
# 			data.frame(feature = this_feature,roc = this_feature_perf_auc@y.values[[1]],prc = this_feature_perf_aucpr@y.values[[1]])
# 		)
# }

#binary activation data feature selection function

find_feature_correlations <- function(row_indexes = NA, all_data) {
	if (is.na(row_indexes)) {
		row_indexes = 1:dim(all_data)[1]
	}
	
	all_cor = cor(
		all_data %>% 
									pull(ic50),
								
		all_data %>% 
									select(starts_with(c('exp')))
		) %>%
		as.data.frame() %>%
		pivot_longer(everything(), names_to = "feature",values_to = "cor")
	
	
	all_correlations = all_cor %>% 
		mutate(abs_cor = abs(cor)) %>% 
		arrange(desc(abs_cor)) %>% 
		mutate(rank = 1:n()) %>%
		mutate(feature_type = case_when(
			str_detect(feature, "^exp_") ~ "Expression",
			T ~ feature
		))

	return(all_correlations)	
}

#excluding wild ic50 values
binary_data_filtered = binary_data %>% 
	filter(ic50 < 30) %>%
	filter(ic50 > 0.0001) %>% 
	mutate(ic50 = log10(ic50))

binary_feat_cors = find_feature_correlations(all_data = binary_data)

number_of_activation_features = 
	dim(binary_data_filtered %>% 
	select(starts_with("act_")))[2]
```

```{r}
#act_PTPN1 true false table

# act_CHD4_data = all_binary_model_data %>% 
# 	select(ic50_binary, act_CHD4) %>% 
# 	count(ic50_binary, act_CHD4)
# 
# temp = all_binary_model_data %>% 
# 	count(ic50_binary, exp_PROSER2)
# 
# summary = variable_genes %>% 
# 	group_by(feature) %>% 
# 	summarise(mean = mean(value))
# 
# summary %>%
# 	ggplot(aes(x = mean)) +
# 	geom_histogram()
```

```{r}
# #binary hit modelling
# 
# build_classification_viability_set = function(num_features, all_data, feature_correlations) {
# 	this_data_filtered = all_data %>% 
# 		select(starts_with("act_"), 
# 					 any_of(feature_correlations$feature[1:num_features]),
# 					 depmap_id,
# 					 ccle_name,
# 					 ic50,
# 					 broad_id,
# 					 ic50_binary)
# }
# 
# get_classification_cv_metrics = function(features, data) {
# this_dataset = build_classification_viability_set(feature_cor =  binary_feat_cors, 
# 	                                                 num_features = features, 
# 	                                                 all_data = data)
# 	
# folds = vfold_cv(this_dataset, v = 10)
# 
# this_recipe = recipe(ic50_binary ~ ., this_dataset) %>%
# 	update_role(-starts_with("act_"),
# 							-starts_with("exp_"),
# 							-starts_with("ic50_binary"),
# 							new_role = "id variable")
# 
# rand_forest_spec <- rand_forest(
# 	trees = 500
# ) %>% set_engine("ranger") %>%
# 	set_mode("classification")
# 
# this_wflow <- 
#   workflow() %>% 
#   add_model(rand_forest_spec) %>% 
#   add_recipe(this_recipe)
# 
# ctrl <- control_resamples(save_pred = TRUE)
# 
# fit <- 
#   this_wflow %>% 
#   fit_resamples(folds, control = ctrl)
# 
# cv_metrics_classification = collect_metrics(fit)
# 
# return(cv_metrics_classification)
# 
# }
# 
# feature_list = c(500, 1000 , 1500, 2000, 2500, 3000, 3500, 4000)
# 
# all_binary_classification_metrics = data.frame()
# for (i in 1:length(feature_list)) {
#   this_metrics = get_classification_cv_metrics(features = feature_list[i], data = binary_data_filtered) %>% 
#     mutate(feature_number = feature_list[i])
#   all_binary_classification_metrics = bind_rows(all_binary_classification_metrics, this_metrics)
# }
# 
# write_csv(all_binary_classification_metrics, here('results/klaeger_LINCS_binary_hit_classification_results.csv'))
```

```{r}
#all data feature selection

find_all_data_feature_correlations <- function(row_indexes = NA, all_data) {
	if (is.na(row_indexes)) {
		row_indexes = 1:dim(all_data)[1]
	}
	
	all_cor = cor(
		all_data %>% 
									pull(ic50),
								
		all_data %>% 
									select(starts_with(c('act','exp')))
		) %>%
		as.data.frame() %>%
		pivot_longer(everything(), names_to = "feature",values_to = "cor")
	
	
	all_correlations = all_cor %>% 
		mutate(abs_cor = abs(cor)) %>% 
		arrange(desc(abs_cor)) %>% 
		mutate(rank = 1:n()) %>%
		mutate(feature_type = case_when(
			str_detect(feature, "^act_") ~ "Activation",
			str_detect(feature, "^exp_") ~ "Expression",
			T ~ feature
		))

	return(all_correlations)	
}

#excluding wild ic50 values
all_data_filtered = all_model_data %>% 
	filter(ic50 < 30) %>%
	filter(ic50 > 0.0001) %>% 
	mutate(ic50 = log10(ic50))

all_data_more_filtered = all_model_data %>% 
	filter(ic50 < 10) %>%
	filter(ic50 > 0.001) %>% 
	mutate(ic50 = log10(ic50))

all_data_feat_cors = find_all_data_feature_correlations(all_data = all_data_filtered)
all_filtered_data_feat_cors = find_all_data_feature_correlations(all_data = all_data_more_filtered)


write_csv(all_data_filtered, here('results/all_model_data.csv'))
write_csv(all_data_more_filtered, here('results/all_model_data_filtered.csv'))
write_csv(all_data_feat_cors, here('results/all_data_feature_correlations.csv'))
write_csv(all_filtered_data_feat_cors, here('results/all_filtered_data_feature_correlations.csv'))
```


```{r}
#all data modelling

# build_all_data_classification_viability_set = function(num_features, all_data, feature_correlations) {
# 	this_data_filtered = all_data %>%
# 		select(any_of(feature_correlations$feature[1:num_features]),
# 					 depmap_id,
# 					 ccle_name,
# 					 ic50,
# 					 broad_id,
# 					 ic50_binary)
# }
# 
# get_all_data_classification_cv_metrics = function(features, data) {
# this_dataset = build_all_data_classification_viability_set(feature_cor =  all_data_feat_cors,
# 	                                                 num_features = features,
# 	                                                 all_data = data)
# 
# folds = vfold_cv(this_dataset, v = 10)
# 
# this_recipe = recipe(ic50_binary ~ ., this_dataset) %>%
# 	update_role(-starts_with("act_"),
# 							-starts_with("exp_"),
# 							-starts_with("ic50_binary"),
# 							new_role = "id variable")
# 
# rand_forest_spec <- rand_forest(
# 	trees = 500
# ) %>% set_engine("ranger") %>%
# 	set_mode("classification")
# 
# this_wflow <-
#   workflow() %>%
#   add_model(rand_forest_spec) %>%
#   add_recipe(this_recipe)
# 
# ctrl <- control_resamples(save_pred = TRUE)
# 
# fit <-
#   this_wflow %>%
#   fit_resamples(folds, control = ctrl)
# 
# cv_metrics_classification = collect_metrics(fit)
# 
# return(cv_metrics_classification)
# 
# }
# 
# feature_list = c(500, 1000 , 1500, 2000, 2500, 3000, 3500, 4000)
# 
# all_data_classification_metrics = data.frame()
# for (i in 1:length(feature_list)) {
#   this_metrics = get_all_data_classification_cv_metrics(features = feature_list[i], data = all_data_filtered) %>%
#     mutate(feature_number = feature_list[i])
#   all_data_classification_metrics = bind_rows(all_data_classification_metrics, this_metrics)
# }
# 
# write_csv(all_data_classification_metrics, here('results/klaeger_LINCS_classification_results.csv'))
```

```{r}
#final 500 feat model

all_data_filtered = read_csv(here('results/all_model_data_filtered.csv'))

all_data_filtered = all_data_filtered %>% 
		mutate(ic50_binary = as.factor(if_else(
		ic50 <= median(all_data_filtered$ic50),
		1,
		0
	)))
all_data_feat_cors =  read_csv(here('results/all_filtered_data_feature_correlations.csv'))

build_all_data_classification_viability_set = function(num_features, all_data, feature_correlations) {
	this_data_filtered = all_data %>%
		select(any_of(feature_correlations$feature[1:num_features]),
					 depmap_id,
					 ccle_name,
					 ic50,
					 broad_id,
					 ic50_binary)
}

features = 500
data = all_data_filtered

this_dataset = build_all_data_classification_viability_set(feature_cor =  all_data_feat_cors,
	                                                 num_features = features,
	                                                 all_data = data)

folds = vfold_cv(this_dataset, v = 10)

this_recipe = recipe(ic50_binary ~ ., this_dataset) %>%
	update_role(-starts_with("act_"),
							-starts_with("exp_"),
							-starts_with("ic50_binary"),
							new_role = "id variable")

rand_forest_spec <- rand_forest(
	trees = 500
) %>% set_engine("ranger") %>%
	set_mode("classification")

this_wflow <-
  workflow() %>%
  add_model(rand_forest_spec) %>%
  add_recipe(this_recipe)

ctrl <- control_resamples(save_pred = TRUE)

fit <-
  this_wflow %>%
  fit_resamples(folds, control = ctrl)

feat500_cv_metrics_classification = collect_metrics(fit)

feat500_classification_predictions = collect_predictions(fit)

roc_curve = feat500_classification_predictions %>%
	roc_curve(truth = ic50_binary, .pred_0) %>%
	autoplot() + 
	ggtitle(round(feat500_cv_metrics_classification$mean[2], 4))

pr_curve = feat500_classification_predictions %>%
	pr_curve(truth = ic50_binary, .pred_0) %>%
	autoplot() +
	ggtitle(round(feat500_cv_metrics_classification$mean[1], 4))

c = roc_curve + pr_curve + plot_annotation(title = '10-fold CV 500 feature Classification Model Results',
																					 subtitle = 'Classify Responsive ic50s')

ggsave(here('figures/500_feat_all_data_classification_model_results.png'))

write_rds(fit, here('results/500feat_all_data_classification_model.rds'))

```


