---
	title: "Assess regression Models"
author: "Chinmaya Joisa"
date: "`r Sys.Date()`"
output: github_document
---
	
```{r}
library(tidyverse)
library(here)
library(tidymodels)
library(ROCR)
library(patchwork)
library(tictoc)
library(broom)
library(gghighlight)
library(Metrics)
library(vroom)
library(conflicted)
library(vip)
conflict_prefer("slice", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("vi", "vip")
conflict_prefer("rmse", "Metrics")
```

# Rand Forest, XGBoost Model Assessment

```{r}
tic()
all_rf_metrics = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	this_model_results = read_rds(
		here('results/PRISM_LINCS_klaeger_models_ic50/activation_expression/regression/rand_forest/results',
				 sprintf('%dfeat.rds.gz',feature_number)))

	this_model_metrics = collect_metrics(this_model_results) %>%
		arrange(desc(mean)) %>%
		slice(1) %>%
		mutate(num_features = feature_number)
	all_rf_metrics = bind_rows(all_rf_metrics, this_model_metrics)
}

all_xgb_metrics = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	this_model_results = read_rds(
		here('results/PRISM_LINCS_klaeger_models_ic50/activation_expression/regression/xgboost/results',
				 sprintf('%dfeat.rds.gz',feature_number)))

	this_model_metrics = collect_metrics(this_model_results) %>%
		arrange(desc(mean)) %>%
		slice(1) %>%
		mutate(num_features = feature_number)
	all_xgb_metrics = bind_rows(all_xgb_metrics, this_model_metrics)
}

all_lr_metrics = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000)) {
	this_model_results = read_rds(
		here('results/PRISM_LINCS_klaeger_models_ic50/activation_expression/regression/lr/results',
				 sprintf('%dfeat.rds.gz',feature_number)))

	this_model_metrics = show_best(this_model_results, metric = "rsq") %>% 
		mutate(num_features = feature_number)
	all_lr_metrics = bind_rows(all_lr_metrics, this_model_metrics)
}


all_NN_metrics = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	this_model_results = read_rds(
		here('results/PRISM_LINCS_klaeger_models_ic50/activation_expression/regression/NN/results',
				 sprintf('%dfeat.rds.gz',feature_number)))

	this_model_metrics = collect_metrics(this_model_results) %>%
		arrange(desc(mean)) %>%
		slice(1) %>%
		mutate(num_features = feature_number)
	all_NN_metrics = bind_rows(all_NN_metrics, this_model_metrics)
}

all_model_metrics = all_rf_metrics %>% 
	pivot_longer(trees, names_to = 'hyperparameter', values_to = 'value') %>%
	mutate(model_type = 'random_forest') %>%
	bind_rows(
		all_xgb_metrics %>%
			pivot_longer(c(trees, tree_depth), names_to = 'hyperparameter', values_to = 'value') %>%
			mutate(model_type = 'xgboost')
	) %>%
	bind_rows(
		all_lr_metrics %>%
			mutate(model_type = 'lasso', hyperparameter = "NA", value = 0)
	) %>% 
	bind_rows(
		all_NN_metrics %>%
			pivot_longer(c(hidden_units, penalty), names_to = 'hyperparameter', values_to = 'value') %>%
			mutate(model_type = 'NN')
	) %>%
	mutate(.config = paste0(.config, '_',model_type)) %>% 
	rename('model_id' = .config) %>% 
	mutate(data_type = "inhibition_expression")

write_csv(all_model_metrics, here('results/PRISM_LINCS_klaeger_models_ic50/activation_expression/regression/all_model_metrics.csv'))

```


#All data models assessment 
```{r}

all_lr_all_data_metrics = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000,3000)) {
	this_model_results = read_rds(
		here('results/PRISM_LINCS_klaeger_models_ic50/all_datasets/regression/lr/results',
				 sprintf('%dfeat.rds.gz',feature_number)))

	this_model_metrics = show_best(this_model_results, metric = "rsq") %>%
		mutate(num_features = feature_number)
	all_lr_all_data_metrics = bind_rows(all_lr_all_data_metrics, this_model_metrics)
}

all_rf_all_data_metrics = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	this_model_results = read_rds(
		here('results/PRISM_LINCS_klaeger_models_ic50/all_datasets/regression/rand_forest/results',
				 sprintf('%dfeat.rds.gz',feature_number)))

		this_model_metrics = collect_metrics(this_model_results) %>%
		arrange(desc(mean)) %>%
		slice(1) %>%
		mutate(num_features = feature_number)
	all_rf_all_data_metrics = bind_rows(all_rf_all_data_metrics, this_model_metrics)
}

all_xgb_all_data_metrics = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	this_model_results = read_rds(
		here('results/PRISM_LINCS_klaeger_models_ic50/all_datasets/regression/xgboost/results',
				 sprintf('%dfeat.rds.gz',feature_number)))
	
		this_model_metrics = collect_metrics(this_model_results) %>%
		arrange(desc(mean)) %>% 
		slice(1) %>% 
		mutate(num_features = feature_number)
	all_xgb_all_data_metrics = bind_rows(all_xgb_all_data_metrics, this_model_metrics)
}


all_NN_all_data_metrics = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	this_model_results = read_rds(
		here('results/PRISM_LINCS_klaeger_models_ic50/all_datasets/regression/NN/results',
				 sprintf('%dfeat.rds.gz',feature_number)))

		this_model_metrics = collect_metrics(this_model_results) %>%
		arrange(desc(mean)) %>%
		slice(1) %>%
		mutate(num_features = feature_number)
	all_NN_all_data_metrics = bind_rows(all_NN_all_data_metrics, this_model_metrics)
}

all_model_all_data_metrics = all_rf_all_data_metrics %>% 
	pivot_longer(trees, names_to = 'hyperparameter', values_to = 'value') %>% 
	mutate(model_type = 'random_forest') %>% 
	bind_rows(
		all_xgb_all_data_metrics %>% 
			pivot_longer(c(trees, tree_depth), names_to = 'hyperparameter', values_to = 'value') %>% 
			mutate(model_type = 'xgboost')
	) %>% 
	bind_rows(
		all_lr_all_data_metrics %>%
			mutate(hyperparameter = NA, value = 0) %>%
			mutate(model_type = 'lasso')
	) %>%
	bind_rows(
		all_NN_all_data_metrics %>%
			pivot_longer(c(hidden_units, penalty), names_to = 'hyperparameter', values_to = 'value') %>%
			mutate(model_type = 'NN')
	) %>%
	mutate(.config = paste0(.config, '_',model_type)) %>% 
	rename('model_id' = .config) %>% 
	mutate(data_type = "all_datasets")

write_csv(all_model_all_data_metrics, here('results/PRISM_LINCS_klaeger_models_ic50/all_datasets/regression/all_model_metrics.csv'))
```

```{r}
#add in high feature xgboost runs
all_xgb_high_feature_metrics = data.frame()
for (feature_number in c(6000,7000,8000,9000)) {
	this_model_results = read_rds(
		here('results/PRISM_LINCS_klaeger_models_ic50/activation_expression/regression/xgboost/results',
				 sprintf('%dfeat.rds',feature_number)))

	this_model_metrics = collect_metrics(this_model_results) %>%
		arrange(desc(mean)) %>%
		slice(1) %>%
		mutate(num_features = feature_number)
	all_xgb_high_feature_metrics = bind_rows(all_xgb_high_feature_metrics, this_model_metrics)
}
```

```{r}
#add in keras NN metrics
keras_metrics = read_csv(here('results/PRISM_LINCS_klaeger_models_ic50/activation_expression/regression/keras/results/best_hyperparameter_search_metrics.csv')) %>%
	mutate(
		layers = case_when(
		layers == "one_layer" ~ '1',
		layers == "two_layer" ~ '2', 
		layers == "four_layer" ~ '4',
		layers == "six_layer" ~ '6', 
		T ~ layers
					)
	) %>%
	mutate(layers = as.numeric(layers)) %>% 
	pivot_longer(c(dropout, neurons, layers, mean_epochs), names_to = "hyperparameter", values_to = "value") %>% 
	mutate(model_type = "4-layer NN",
				 data_type = "inhibition_expression",
				 .metric = "rsq", 
				 n = 5) %>%
	rename("mean" = mean_rsq, 
				 "std_err" = sd_rsq)

keras_all_data_metrics = read_csv(here('results/PRISM_LINCS_klaeger_models_ic50/all_datasets/regression/keras/results/best_hyperparameter_search_metrics.csv')) %>%
	mutate(
		layers = case_when(
		layers == "one_layer" ~ '1',
		layers == "two_layer" ~ '2', 
		layers == "four_layer" ~ '4',
		layers == "six_layer" ~ '6', 
		T ~ layers
					)
	) %>%
	mutate(layers = as.numeric(layers)) %>% 
	pivot_longer(c(dropout, neurons, layers, mean_epochs), names_to = "hyperparameter", values_to = "value") %>% 
	mutate(model_type = "4-layer NN",
				 data_type = "all_datasets",
				 .metric = "rsq", 
				 n = 5) %>%
	rename("mean" = mean_rsq, 
				 "std_err" = sd_rsq)
```

```{r}
#add in missing lasso results
missing_lr_metrics = data.frame()
for (feature_number in c(3000,4000,5000)) {
	this_model_results = read_rds(
		here('results/PRISM_LINCS_klaeger_models_ic50/activation_expression/regression/lr/results',
				 sprintf('%dfeat.rds.gz',feature_number)))

	this_model_metrics = show_best(this_model_results, metric = "rsq") %>% 
		mutate(num_features = feature_number)
	missing_lr_metrics = bind_rows(missing_lr_metrics, this_model_metrics)
}

missing_lr_metrics = missing_lr_metrics %>% 
	mutate(hyperparameter = NA, value = 0) %>%
	mutate(model_type = 'lasso',
				 data_type = "inhibition_expression") 

missing_lr_all_data_metrics = data.frame()
for (feature_number in c(4000,5000)) {
	this_model_results = read_rds(
		here('results/PRISM_LINCS_klaeger_models_ic50/all_datasets/regression/lr/results',
				 sprintf('%dfeat.rds.gz',feature_number)))

	this_model_metrics = show_best(this_model_results, metric = "rsq") %>%
		mutate(num_features = feature_number)
	missing_lr_all_data_metrics = bind_rows(missing_lr_all_data_metrics, this_model_metrics)
}

missing_lr_all_data_metrics = missing_lr_all_data_metrics %>% 
	mutate(hyperparameter = NA, value = 0) %>%
	mutate(model_type = 'lasso',
				 data_type = "all_datasets")

all_missing_lr_metrics = missing_lr_metrics %>% 
	bind_rows(missing_lr_all_data_metrics)

```


```{r}
all_model_metrics = read_csv(here('results/PRISM_LINCS_klaeger_models_ic50/activation_expression/regression/all_model_metrics.csv'))
all_model_all_data_metrics = read_csv(here('results/PRISM_LINCS_klaeger_models_ic50/all_datasets/regression/all_model_metrics.csv'))
	
model_metrics_combined = all_model_all_data_metrics %>% 
	bind_rows(all_model_metrics) %>% 
	filter(!model_type == "NN") %>% 
	bind_rows(keras_metrics) %>% 
	bind_rows(keras_all_data_metrics) %>% 
	bind_rows(all_missing_lr_metrics) %>% 
	select(-mean_rmse, -sd_rmse, -mean_loss, -sd_loss, -.estimator) %>% 
	mutate(target = "AUC")

write_csv(model_metrics_combined, here('results/PRISM_LINCS_klaeger_models_ic50/PRISM_LINCS_klaeger_models_ic50_regression_metrics.csv'))
```

```{r}
# metrics figure
model_metrics_combined %>%
	ggplot(aes(x = num_features, y = mean, colour = model_type, shape = model_type)) +
	geom_point() + 
  # geom_errorbar(aes(ymin=mean-std_err, ymax=mean+std_err), width=.2,
  #                position=position_dodge(.9)) +
	coord_cartesian(ylim= c(0.35,0.7)) +
	facet_wrap(vars(target, data_type), scales = "free_x") +
	labs(title = "AUC Models", x = "number of features", y = "R-squared") +
		theme(
		legend.position = "right",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )

ggsave(here('figures/PRISM_LINCS_klaeger/all_regression_models_ic50_metrics.png'))

#final metrics figure
# model_metrics_combined %>% 
# 	ggplot(aes(x = num_features, y = mean, colour = data_type, shape = data_type)) +
# 	geom_point() + 
#   geom_errorbar(aes(ymin=mean-std_err, ymax=mean+std_err), width=.2,
#                  position=position_dodge(.9)) +
# 	coord_cartesian(ylim= c(0.2,0.68)) +
# 	labs(title = "AUC Models", x = "number of features", y = "R-squared") +
# 	facet_wrap(vars(model_type)) +
# 		theme(
# 		legend.position = "top",
# 		legend.text = element_text(size = 9),
# 		legend.background = element_rect(fill = "transparent",colour = NA),
# 		panel.background = element_rect(fill = "transparent",colour = NA),
#     panel.grid.minor = element_blank(), 
#     panel.grid.major = element_blank(),
#     plot.background = element_rect(fill = "transparent",colour = NA)
#       )
# 
# ggsave(here('figures/PRISM_LINCS_klaeger/all_regression_models_ic50_metrics.png'), width = 10.5, height = 10.5, units = "cm")
```

```{r}
#extract best all data model
best_all_data_model = model_metrics_combined %>% 
	dplyr::filter(data_type == "all_datasets") %>% 
	arrange(desc(mean)) %>% 
	filter(model_id == model_id[1] & num_features == num_features[1]) %>% 
	pivot_wider(names_from = hyperparameter, values_from = value)
```

```{r}
#fit best all data model 
args = data.frame(feature_num = best_all_data_model$num_features)
print(sprintf('Features: %02d',args$feature_num))

this_dataset = read_rds(here('results/PRISM_LINCS_klaeger_all_multiomic_data_for_ml_5000feat_ic50.rds'))
cors = vroom(here('results/PRISM_LINCS_klaeger_all_multiomic_data_feature_correlations_ic50.csv'))

folds = read_rds(here('results/PRISM_LINCS_klaeger_all_multiomic_data_folds_ic50.rds'))

this_recipe = recipe(ic50 ~ ., this_dataset) %>%
	update_role(-starts_with("act_"),
							-starts_with("exp_"),
							-starts_with("cnv_"),
							-starts_with("prot_"),
							-starts_with("dep_"),
							-starts_with("ic50"),
							new_role = "id variable") %>%
	step_select(depmap_id,
							ccle_name,
							ic50,
							broad_id,
							any_of(cors$feature[1:args$feature_num])) %>% 
	step_normalize(all_predictors())

xgb_spec <- boost_tree(
	trees = best_all_data_model$trees, 
	tree_depth = best_all_data_model$tree_depth                  
) %>% 
	set_engine("xgboost") %>% 
	set_mode("regression")

this_wflow <-
	workflow() %>%
	add_model(xgb_spec) %>%
	add_recipe(this_recipe) 

race_ctrl = control_resamples(
	save_pred = TRUE, 
	parallel_over = "everything",
	verbose = TRUE
)

set.seed(2222)
results <- fit_resamples(
	this_wflow,
	resamples = folds,
	control = race_ctrl
) %>% 
	write_rds(here('results/final_tuned_PRISM_LINCS_klaeger_ic50_regression_model_all_datasets.rds'))
toc()

final_metrics = collect_metrics(results)
final_predictions = collect_predictions(results, ) %>% 
	rename("predicted_ic50" = .pred)
```

```{r}
#final figure
final_predictions %>%
	ggplot(aes(x = predicted_ic50, y = ic50)) +
	geom_hex() +
	scale_fill_viridis_c() +
	labs(title = 
			 	paste0('R\u00B2 = ',
			 				 round(
			 				 	final_metrics$mean[2],
			 				 	2),
			 				 ' / ',
			 				 'RMSE = ',
			 				 round(
			 				 	final_metrics$mean[1],
			 				 	2)
			 	),
			 x = "Predicted AUC",
			 y = "Actual AUC") +
	geom_abline(intercept = 0, slope = 1, size = 0.3, colour = 'black', linetype = 3) +
	geom_smooth(colour = "red") +
	coord_cartesian(xlim = c(0.2,1), ylim= c(0,1)) +
	theme(
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )

ggsave(here('figures/final_tuned_PRISM_LINCS_klaeger_ic50_regression_model.png'), width = 10.5, height = 10.5, units = "cm")
```



