---
title: "Make Model Predictions"
output: html_document
date: '2022-03-09'
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(ROCR)
library(patchwork)
library(tictoc)
library(broom)
library(gghighlight)
library(Metrics)
library(vroom)
library(conflicted)
library(vip)
conflict_prefer("slice", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("vi", "vip")
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#read in data
data = vroom(here('results/PRISM_LINCS_klaeger_data_for_ml_5000feat.csv'))
cors =  vroom(here('results/PRISM_LINCS_klaeger_data_feature_correlations.csv'))
```

```{r}
#extract best act-exp model
model_metrics_combined = read_csv(here('results/PRISM_LINCS_klaeger_ic50_models_regression_metrics.csv')) %>% 
	mutate(data_type = if_else(
		data_type == "activation_expression",
		"inhibition_expression",
		data_type))

best_act_exp_model = model_metrics_combined %>% 
	dplyr::filter(data_type == "inhibition_expression") %>% 
	arrange(desc(mean)) %>% 
	filter(model_id == model_id[1] & num_features == num_features[1]) %>% 
	pivot_wider(names_from = hyperparameter, values_from = value)
```

```{r}
#fit best act-exp model 
args = data.frame(feature_num = best_act_exp_model$num_features)
print(sprintf('Features: %02d',args$feature_num))

build_all_data_regression_viability_set = function(num_features, all_data, feature_correlations) {
	this_data_filtered = all_data %>%
		select(any_of(feature_correlations$feature[1:num_features]),
					 depmap_id,
					 ccle_name,
					 broad_id,
					 ic50)
}
this_dataset = build_all_data_regression_viability_set(feature_correlations =  cors,
																													 num_features = args$feature_num,
																													 all_data = data)

this_recipe = recipe(ic50 ~ ., this_dataset) %>%
	update_role(-starts_with("act_"),
							-starts_with("exp_"),
							-starts_with("ic50"),
							new_role = "id variable") %>%
	step_normalize(all_predictors())

xgb_spec <- boost_tree(
	trees = best_act_exp_model$trees, 
	tree_depth = best_act_exp_model$tree_depth,       
	learn_rate = best_act_exp_model$learn_rate                   
) %>% 
	set_engine("xgboost", tree_method = "gpu_hist", nthreads = 16, importance_type = "gain") %>% 
	set_mode("regression")

this_wflow <-
	workflow() %>%
	add_model(xgb_spec) %>%
	add_recipe(this_recipe) 

results = this_wflow %>% 
	fit(data = this_dataset) %>% 
	write_rds(here('results/final_tuned_PRISM_LINCS_klaeger_ic50_regression_model.rds'))

# results = read_rds(here('results/final_tuned_PRISM_LINCS_klaeger_regression_model.rds'))
# final_metrics = collect_metrics(results)
# final_predictions = collect_predictions(results) %>% 
# 	rename("predicted" = .pred)
```

```{r}
#Variable Importance
results = read_rds(here('results/final_tuned_PRISM_LINCS_klaeger_ic50_regression_model.rds'))

all_importance = vi(results %>% extract_fit_parsnip()) %>%
		mutate(feature_type = case_when(
			str_detect(Variable, "^act_") ~ "Inhibition",
			str_detect(Variable, "^exp_") ~ "Expression",
			str_detect(Variable, "^dep_") ~ "Depmap",
			str_detect(Variable, "^cnv_") ~ "CNV",
			str_detect(Variable, "^prot_") ~ "Proteomics",
			T ~ Variable
		)) %>% 
	separate(Variable, into = c('prefix', 'Variable'), sep = "_") %>% 
	select(-prefix) %>% 
	arrange(Importance) %>%
	mutate(Variable = fct_inorder(Variable))

ggplot(all_importance %>% slice_tail(n = 25), 
			 aes(x=Importance,y=Variable)) + 
	geom_col() +
	labs(title = "IC50 model importances",y='',x='Feature Importance') +
	theme(legend.justification = c(1, 0), legend.position = c(1, 0)) +
	scale_fill_brewer(type='qual', palette = "Dark2") +
	theme(
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA))
		
ggsave(here('figures/ic50_regression_top_25_VIP.png'),width=5,height=3.75)
```

```{r}
inhibition_importances = all_importance %>% 
	filter(feature_type == "Inhibition") %>% 
	write_csv(here('results/ic50_inhibition_feature_importances.csv'))

expression_importances = all_importance %>% 
	filter(feature_type == "Expression") %>% 
	write_csv(here('results/ic50_expression_feature_importances.csv'))
```


