```{r}
library(tidyverse)
library(here)
library(reticulate)
library(vroom)
library(DarkKinaseTools)
#py_install("shap")
py_install("matplotlib")
```

```{r}
#read in data 
data = read_rds(here('results/PRISM_LINCS_klaeger_models_auc/PRISM_LINCS_klaeger_data_for_ml_5000feat_auc.rds.gz'))

cors =  vroom(here('results/PRISM_LINCS_klaeger_models_auc/PRISM_LINCS_klaeger_data_feature_correlations_auc.csv'))

gene_classifications = read_csv(here('data/KlaegerScience2017/manual_gene_labels.csv')) %>%
	bind_rows(all_kinases %>% select(symbol,class) %>% rename(gene_name = symbol)) %>% 
	#adding extra label for abbreviated activation name
	bind_rows(data.frame(gene_name = "CSNK2A(1/3)", class = "Light")) %>%
	distinct() %>% 
	mutate(gene_name = str_replace(gene_name, "[-;]", "_")) %>% 
	mutate(gene_name = if_else(
		gene_name == 'HIST2H2BE_HIST1H2BB;HIST1H2BO;HIST1H2BJ;HIST3H2BB;HIST1H2BA',
		'HIST2H2BE_HIST1H2BB_HIST1H2BO_HIST1H2BJ_HIST3H2BB_HIST1H2BA',
		gene_name
	))

exp_interactor_type = read_rds(here('results/PRISM_LINCS_klaeger_models_auc/expression_feature_interactors.rds')) %>%
	mutate(Variable = paste0(type,"_",hgnc)) %>%
	mutate(interaction = case_when(
		direct_count >= 1 ~ "Inhibition\nInteractor",
		T ~ "Noninterator"
	))
```

```{python}
import numpy as np
import pandas as pd
from sklearn.metrics import average_precision_score, precision_recall_curve, roc_auc_score, roc_curve
from sklearn.model_selection import train_test_split
import tensorflow as tf
from math import sqrt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost.sklearn import XGBClassifier
import csv
#shap requires this setting and tf.keras instead of keras to work
tf.compat.v1.disable_v2_behavior()
```

```{python}
#data preprocessing
data = r.data
feats = r.cors
feats_list = feats['feature'][:2000].tolist()
feats_list.append('auc')
ids = ['broad_id','ccle_name','depmap_id','auc_binary']
#add ids to feats_list
feats_list.extend(ids)
data = data[feats_list]
exclude = ['auc','broad_id','ccle_name','depmap_id','auc_binary']
y = data['auc']
X = data.drop(exclude, axis=1)
```

```{python}

#define model
input_shape = [X.shape[1]]
model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Flatten(input_shape=input_shape))
    for layer in range(4):
        model.add(tf.keras.layers.BatchNormalization())
        model.add(tf.keras.layers.Dense(200))
        model.add(tf.keras.layers.Dropout(0.2))
        model.add(tf.keras.layers.Activation("relu"))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(1, activation='linear'))

    optimizer = tf.keras.optimizers.Adam(learning_rate=0.003)
    
    model.compile(loss="mean_squared_error", metrics=['RootMeanSquaredError'], optimizer=optimizer)
    
early_stopping = tf.keras.callbacks.EarlyStopping(
    patience=25,
    min_delta=0.001,
    restore_best_weights=True,)

history = model.fit(
    X, y,
    batch_size=512,
    epochs=200)
```

```{python}
#calculate shap values
import shap
import matplotlib
explainer = shap.DeepExplainer(model, X.sample(n=4000))
shap_values = explainer.shap_values(X.sample(n=4000).values)
```

```{python}
#put the shap values into a dataframe
shap_values[0].shape
vals = np.abs(shap_values[0]).mean(0)
feature_names = X.columns
feature_importance = pd.DataFrame(list(zip(feature_names, vals)),
                                  columns=['col_name','feature_importance_vals'])
feature_importance.sort_values(by=['feature_importance_vals'],
                               ascending=False, inplace=True)
feature_importance.head(10)
```

```{r}
shap_values = py$feature_importance

shap_values_processed = shap_values %>% 
	rename(feature = col_name,
				 shap_value = feature_importance_vals) %>%  
	arrange((shap_value)) %>%
	mutate(feature_type = case_when(
			str_detect(feature, "^act_") ~ "Inhibition",
			str_detect(feature, "^exp_") ~ "Expression",
			str_detect(feature, "^dep_") ~ "Depmap",
			str_detect(feature, "^cnv_") ~ "CNV",
			str_detect(feature, "^prot_") ~ "Proteomics",
			T ~ feature
		)) %>% 
	write_csv(here('results/PRISM_LINCS_klaeger_models_auc/all_feature_shap_values.csv'))

shap_inhibition = shap_values_processed %>% 
	filter(feature_type == "Inhibition") %>% 
	mutate(feature = ifelse(feature == "act_CSNK2A1_CSNK2A3","act_CSNK2A(1/3)",feature)) %>%
	extract(feature, c(NA,"gene"),"(.*)_(.*)",remove=F) %>%
	left_join(gene_classifications, by=c('gene'='gene_name')) %>%
	mutate(class = ifelse(is.na(class), "Non-kinase",class)) %>% 
	arrange(desc(shap_value)) 

shap_expression = shap_values_processed %>% 
	filter(feature_type == "Expression") %>% 
	extract(feature, c(NA,"gene"),"(.*)_(.*)",remove=F) %>%
	left_join(exp_interactor_type %>% select(Variable,interaction) %>% rename(feature = Variable)) %>% 
	arrange(desc(shap_value))
	
shap_inhibition %>%
  slice(1:25) %>%
	arrange(shap_value) %>% 
	mutate(gene = fct_inorder(gene)) %>% 
	ggplot(aes(x = shap_value, y = gene, fill = class)) +
	geom_col() +
	labs(y='',fill='',x='Feature Importance') +
	theme(
		legend.title = element_blank(),
		legend.position = "bottom",
		legend.direction = "vertical",
		legend.margin = margin(t = 0, b = 0, l = 0, r = 0, unit = "cm"),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )
ggsave(here('figures/PRISM_LINCS_klaeger/inhibition_shap_figure.png'), height = 10.5, width = 7, units = "cm")

shap_expression %>%
  slice(1:25) %>%
	arrange(shap_value) %>% 
	unique() %>% 
	mutate(gene = fct_inorder(gene)) %>% 
	ggplot(aes(x = shap_value, y = gene, fill = interaction)) +
	geom_col() +
	labs(y='',fill='',x='Feature Importance') +
	scale_x_continuous(breaks = c(0, 5e-4,1e-3)) +
	theme(
		legend.title = element_blank(),
		legend.position = "bottom",
		legend.direction = "vertical",
		legend.margin = margin(t = 0, b = 0, l = 0, r = 0, unit = "cm"),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )
ggsave(here('figures/PRISM_LINCS_klaeger/expression_shap_figure.png'), height = 10.5, width = 7, units = "cm")
```


