#Plot Relative Performance on KINOMESCAN vs Klaeger Data by model type

```{r}
library(tidyverse)
library(patchwork)
library(here)
library(vroom)
```

```{r}
#read in data
final_comparisons = read_csv(here('results/PRISM_LINCS_klaeger_models_ic50/PRISM_LINCS_klaeger_data_origin_comparison_metrics_ic50.csv'))
```

```{r}
#reorder levels of model_type and build figure
#title = "KINOMEscan R\u00B2 / \n Kinobeads R\u00B2",

final_comparisons %>% 
	mutate(model_type = case_when(
			model_type == "random forest" ~ "Random Forest",
			model_type == "lasso" ~ "Lasso",
			model_type == "xgboost" ~ "XGBoost",
			T ~ model_type)) %>% 
	mutate(model_type = as.factor(model_type)) %>% 
	mutate(model_type = fct_relevel(model_type, "Random Forest", "XGBoost", "Lasso", "4-layer Neural Network")) %>% 
	ggplot(aes(x = model_type, y = relative_rsq, shape = model_type, colour = model_type , fill = model_type)) +
	geom_point(alpha = 1.5, size = 3) +
	coord_cartesian(ylim = c(0.6, 1)) +
	scale_shape_manual(values=c(16, 3, 15, 17)) +
	scale_color_manual(values=c('#F8766D', '#C77CFF', '#00BFC4', '#7CAE00')) +
	# scale_fill_manual(values=c('orange', 'purple', 'blue', 'green')) +
	geom_hline(aes(yintercept = 1), linetype = 3) + 
	labs(x = "Model Type", y = "Relative Performance of Models\non KINOMEscan vs Kinobeads", colour = "Model Type", shape = "Model Type") +
		theme(
		legend.position = "none",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
		plot.title = element_text(hjust = 0.5),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )

ggsave(here('figures/PRISM_LINCS_klaeger/data_origin_comparison_figure.png'), width = 4, height = 10.5, units = "cm")
```


