---
	title: "Compare Performance of Xgboost on Klaeger drugs vs Kinomescan drugs"
author: "Chinmaya Joisa"
date: "`r Sys.Date()`"
output: github_document
---
	
```{r}
library(tidyverse)
library(here)
library(tidymodels)
library(ROCR)
library(patchwork)
library(tictoc)
library(broom)
library(gghighlight)
library(Metrics)
library(vroom)
library(conflicted)
library(vip)
conflict_prefer("slice", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("vi", "vip")
conflict_prefer("rmse", "Metrics")
```

```{r}
#read in data 

this_dataset = read_rds(here('results/PRISM_LINCS_klaeger_models_auc/PRISM_LINCS_klaeger_data_for_ml_5000feat_auc.rds.gz'))
cors =  vroom(here('results/PRISM_LINCS_klaeger_models_auc/PRISM_LINCS_klaeger_data_feature_correlations_auc.csv'))

folds = read_rds(here('results/cv_folds/PRISM_LINCS_klaeger_folds_auc.rds.gz'))
```

```{r}
#read in / fit best xgboost model 
if (file.exists(here('results/PRISM_LINCS_klaeger_models_auc/PRISM_LINCS_klaeger_tuned_xgboost_regression_model_auc.rds.gz'))) {
	xgboost_results = read_rds(here('results/PRISM_LINCS_klaeger_models_auc/PRISM_LINCS_klaeger_tuned_xgboost_regression_model_auc.rds.gz'))
} else { 

args = data.frame(feature_num = best_xgboost_model$num_features)
print(sprintf('Features: %02d',args$feature_num))

this_recipe = recipe(auc ~ ., this_dataset) %>%
	update_role(-starts_with("act_"),
							-starts_with("exp_"),
							-starts_with("auc"),
							new_role = "id variable") %>%
	step_select(depmap_id,
							ccle_name,
							auc,
							broad_id,
							any_of(cors$feature[1:args$feature_num])) %>% 
	step_normalize(all_predictors())

xgb_spec <- boost_tree(
	trees = best_xgboost_model$trees, 
	tree_depth = best_xgboost_model$tree_depth                
) %>% 
	set_engine("xgboost", tree_method = "gpu_hist") %>% 
	set_mode("regression")

this_wflow <-
	workflow() %>%
	add_model(xgb_spec) %>%
	add_recipe(this_recipe) 

race_ctrl = control_resamples(
	save_pred = TRUE, 
	parallel_over = "everything",
	verbose = TRUE
)
tic()
xgboost_results <- fit_resamples(
	this_wflow,
	resamples = folds,
	grid = xgb_grid,
	control = race_ctrl
) %>% 
	write_rds(here('results/PRISM_LINCS_klaeger_models_auc/PRISM_LINCS_klaeger_tuned_xgboost_regression_model_auc.rds.gz'),
						compress = "gz")
toc()
}

xgboost_predictions = collect_predictions(xgboost_results) %>% 
	rename("predicted_auc" = .pred)
```

```{r}
# make dataset with rownumbers and drug origin labelled 
compound_match_list = read_csv(here('results/matching/LINCS_PRISM_klaeger_combined_drug_matches_no_overlap.csv'))

dataset_with_rownumbers = this_dataset %>% 
	rownames_to_column(var = "rownumber") %>% 
	select(rownumber,broad_id, depmap_id, auc, ccle_name) %>% 
	left_join(compound_match_list, by = 'broad_id') %>% 
	mutate(origin = if_else(
		is.na(klaeger_name),
		"KINOMEscan",
		"Kinobeads"
	)) %>% 
	select(-klaeger_name, -LINCS_name, -auc) 
```

```{r}

final_full_predictions = xgboost_predictions %>%
	rename("rownumber" = .row) %>% 
	mutate(rownumber = as.character(rownumber)) %>% 
	left_join(dataset_with_rownumbers, by = 'rownumber')

kinomescan_rsq = cor(
	final_full_predictions %>% 
	filter(origin == "KINOMEscan") %>% 
		pull(predicted_auc),
		final_full_predictions %>% 
	filter(origin == "KINOMEscan") %>% 
		pull(auc)
)^2

klaeger_rsq = cor(
	final_full_predictions %>% 
	filter(origin == "Kinobeads") %>% 
		pull(predicted_auc),
		final_full_predictions %>% 
	filter(origin == "Kinobeads") %>% 
		pull(auc)
)^2

kinomescan_rmse = rmse(
	final_full_predictions %>% 
	filter(origin == "KINOMEscan") %>% 
		pull(predicted_auc),
		final_full_predictions %>% 
	filter(origin == "KINOMEscan") %>% 
		pull(auc)
)

klaeger_rmse = rmse(
	final_full_predictions %>% 
	filter(origin == "Kinobeads") %>% 
		pull(predicted_auc),
		final_full_predictions %>% 
	filter(origin == "Kinobeads") %>% 
		pull(auc)
)

```

```{r}
#build comparison figure
a = final_full_predictions %>%
	filter(origin == "KINOMEscan") %>% 
	ggplot(aes(x = predicted_auc, y = auc)) +
	geom_hex() +
	scale_fill_viridis_c() +
	labs(title = 
			 	paste0('KINOMEscan R\u00B2 = ',
			 				 round(
			 				 	kinomescan_rsq,
			 				 	2),
			 				 '/ RMSE = ',
			 				 round(
			 				 	kinomescan_rmse,
			 				 	2)
			 	), 
			 x = "Predicted AUC",
			 y = "Actual AUC") +
	geom_abline(intercept = 0, slope = 1, size = 0.3, colour = 'black', linetype = 3) +
	geom_smooth(colour = "red") +
	coord_cartesian(xlim = c(0.2,1), ylim= c(0,1)) +
	theme(
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )

b = final_full_predictions %>%
	filter(origin == "Kinobeads") %>% 
	ggplot(aes(x = predicted_auc, y = auc)) +
	geom_hex() +
	scale_fill_viridis_c() +
	labs(title = 
			 	paste0('Kinobeads R\u00B2 = ',
			 				 round(
			 				 	klaeger_rsq,
			 				 	2),
			 				 '/ RMSE = ',
			 				 round(
			 				 	klaeger_rmse,
			 				 	2)
			 	), 
			 x = "Predicted AUC",
			 y = "Actual AUC") +
	geom_abline(intercept = 0, slope = 1, size = 0.3, colour = 'black', linetype = 3) +
	geom_smooth(colour = "red") +
	coord_cartesian(xlim = c(0.2,1), ylim= c(0,1)) +
	theme(
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )
c = a+b
ggsave(here('figures/PRISM_LINCS_klaeger/xgboost_klaeger_kinomescan_comparison.png'), height = 8, width = 12)
```

