---
title: "Search Space EDA"
author: "Chinmaya Joisa"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidyHeatmap)
library(wesanderson)

knitr::opts_knit$set(root.dir = here())
```

```{r}
compound_match_list = read_csv(here('results/matching/LINCS_PRISM_klaeger_combined_drug_matches_final.csv'))

PRISM_auc = read_csv(here('results/PRISM_LINCS_klaeger_models_auc/PRISM_auc_for_ml.csv'))

LINCS_klaeger_data_long = read_csv(here('results/all_klaeger_LINCS_data_for_ml_long.csv'))

full_CCLE_expression_set_for_ML = read_rds(here('data/full_CCLE_expression_set_for_ML.rds')) %>% 
	rename('depmap_id' = DepMap_ID)
```

```{r}
#preparing to compare PRISM drug names to klaeger+kinomescan
compound_match_list_processed = compound_match_list %>% 
	mutate(drug = if_else(is.na(klaeger_name), 
												LINCS_name, 
												klaeger_name)) %>% 
	select(drug, broad_id) %>% 
	unique()

PRISM_auc_processed = PRISM_auc %>% 
	left_join(compound_match_list_processed) %>% 
	select(-name)
```

 
```{r}
drug_origins = LINCS_klaeger_data_long %>% 
	select(drug, origin) %>% 
	unique()

all_combos = crossing(
	drug = unique(LINCS_klaeger_data_long$drug),
	depmap_id = unique(full_CCLE_expression_set_for_ML$depmap_id)
) %>% 
	left_join(drug_origins)
	
already_tested = PRISM_auc_processed %>%
	select(drug, depmap_id) %>%
	unique() %>%
	mutate(tested = 1)

cell_line_compound_counts = PRISM_auc_processed %>%
	select(drug,depmap_id) %>%
	unique() %>%
	group_by(depmap_id) %>%
	summarise(num_drugs = n()) %>%
	arrange(desc(num_drugs)) %>%
	mutate(depmap_id = fct_inorder(depmap_id)) %>%
	add_row(depmap_id = unique(full_CCLE_expression_set_for_ML$depmap_id)[!unique(full_CCLE_expression_set_for_ML$depmap_id) %in% unique(PRISM_auc_processed$depmap_id)],
					num_drugs = 0) %>%	
	filter(!depmap_id %in% c('ACH-001024', 'ACH-000979', 'ACH-000047', 'ACH-000309')) %>% 
	mutate(depmap_id_num = 1:n())

drug_line_compound_counts = PRISM_auc_processed %>%
	select(drug,depmap_id) %>%
	unique() %>%
	group_by(drug) %>%
	summarise(num_lines = n()) %>%
	arrange(desc(num_lines)) %>%
	mutate(drug = fct_inorder(drug)) %>%
	add_row(drug = unique(LINCS_klaeger_data_long$drug)[!unique(LINCS_klaeger_data_long$drug) %in% unique(PRISM_auc_processed$drug)],
					num_lines = 0) %>%
	mutate(drug_id_num = 1:n())

all_combos_releveled = all_combos %>% 
	left_join(already_tested) %>%
	mutate(tested = if_else(is.na(tested), 0, 1)) %>% 
	mutate(depmap_id = fct_relevel(depmap_id, as.character(cell_line_compound_counts$depmap_id))) %>% 
	mutate(drug = fct_relevel(drug, as.character(drug_line_compound_counts$drug)))
```

```{r}
all_combos_extra = all_combos_releveled %>%
	left_join(cell_line_compound_counts %>% select(depmap_id, depmap_id_num)) %>%
	left_join(drug_line_compound_counts %>% select(drug, drug_id_num)) %>% 
	left_join(drug_origins)

mean_tested = list(
	x = mean(all_combos_extra %>% filter(tested == 1) %>% pull(depmap_id_num)),
	y = mean(all_combos_extra %>% filter(tested == 1) %>% pull(drug_id_num))
)

mean_not_tested = list(
	x = mean(all_combos_extra %>% filter(tested == 0) %>% pull(depmap_id_num)),
	y = mean(all_combos_extra %>% filter(tested == 0) %>% pull(drug_id_num))
)
```

```{r}
ggplot(all_combos_extra, aes(y=drug_id_num,x=depmap_id_num, fill = as.factor(tested), width=1, height=1)) +
	geom_tile() +
	scale_fill_manual(values = c("white","black","green","red","brown")) +
	theme_void() +
	theme(legend.position = "none") +
	annotate("text",x=mean_tested$x, y=mean_tested$y, 
					 label=paste0(signif(mean(all_combos_extra$tested),3)*100,"% Tested"), color='white') +
	annotate("text",x=mean_not_tested$x, y=mean_not_tested$y, 
					 label=paste0(signif(1-mean(all_combos_extra$tested),3)*100,"% Not Tested")) + 
	annotate("rect", xmin=0, xmax=1379, ymin=0, ymax=1006, alpha=0, fill="white", colour = "black", size = 0.2) +
  annotate("rect", xmin=0, xmax=1379, ymin=0, ymax=212, alpha=0.15, fill= wes_palettes$GrandBudapest2[3]) +
	annotate("text",x=186, y=193, colour = wes_palettes$GrandBudapest2[3],
					 label="Kinobeads Compound Space") + 
	annotate("rect", xmin=0, xmax=1379, ymin=212, ymax=1006, alpha=0.15, fill=wes_palettes$GrandBudapest2[4]) +
	annotate("text",x=204, y=985, colour =wes_palettes$GrandBudapest2[4],
					 label="KINOMEscan Compound Space") 
	
ggsave(here('figures/PRISM_LINCS_klaeger/untested_feature_space_invert.png'), dpi = 300, height=10, width=21, units = "cm")
```

