---
	title: "Assess kevin keras regression"
author: "Chinmaya Joisa"
date: "`r Sys.Date()`"
output: github_document
---
	
```{r}
library(tidyverse)
library(here)
library(tidymodels)
library(ROCR)
library(patchwork)
library(tictoc)
library(broom)
library(gghighlight)
library(Metrics)
library(vroom)
library(conflicted)
library(vip)
conflict_prefer("slice", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("vi", "vip")
conflict_prefer("rmse", "Metrics")
```

#Keras Tuning Assessment

```{r}
#all tuning metrics per feature count

all_keras_scores = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	this_keras_scores = read_csv(
		here('results/PRISM_LINCS_klaeger_models_auc/activation_expression/regression/keras/results',
				 sprintf('hps_keras_%d.csv',feature_number))) %>% 
		mutate(num_features = feature_number) %>% 
		select(num_features, starts_with("param_"), mean_test_score, std_test_score) %>%
		rename(mean_rsq = mean_test_score,
					 std_err = std_test_score)
	all_keras_scores = bind_rows(all_keras_scores, this_keras_scores)
}

write_csv(all_keras_scores, here('results/PRISM_LINCS_klaeger_models_auc/activation_expression/regression/keras/results/hyperparameter_search_metrics.csv'))
```

```{r}
#best metrics per feature count

best_keras_scores = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	this_keras_scores = read_csv(
		here('results/PRISM_LINCS_klaeger_models_auc/activation_expression/regression/keras/results',
				 sprintf('hps_keras_%d.csv',feature_number))) %>% 
		mutate(num_features = feature_number) %>% 
		select(num_features, starts_with("param_"), mean_test_score, std_test_score) %>%
		rename(mean_rsq = mean_test_score,
					 std_err = std_test_score) %>% 
		arrange(desc(mean_rsq)) %>% 
		slice(1)
	
	best_keras_scores = bind_rows(best_keras_scores, this_keras_scores)
}

write_csv(best_keras_scores, here('results/PRISM_LINCS_klaeger_models_auc/activation_expression/regression/keras/results/best_hyperparameter_search_metrics.csv'))
```


```{r}
best_keras_scores %>%
	ggplot(aes(x = num_features, y = rsq)) +
	geom_point() +
#  geom_errorbar(aes(ymin=mean-std_err, ymax=mean+std_err), width=.2,
#                position=position_dodge(.9)) +
	coord_cartesian(ylim= c(0.2,0.68)) +
	labs(title = "Keras Hyperparameter Search", x = "number of features", y = "R-squared") +
#	facet_wrap(vars(model_type)) +
		theme(
		legend.position = "top",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )

ggsave(here('figures/PRISM_LINCS_klaeger/keras_hyperparameter_search_metrics.png'), width = 10.5, height = 10.5, units = "cm")
```

#Keras All Datasets Tuning Assessment

```{r}
#all tuning metrics per feature count

all_data_all_keras_scores = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	this_keras_scores = read_csv(
		here('results/PRISM_LINCS_klaeger_models_auc/all_datasets/regression/keras/results',
				 sprintf('hps_keras_%d.csv',feature_number))) %>% 
		mutate(num_features = feature_number) %>% 
		select(num_features, starts_with("param_"), mean_test_score, std_test_score) %>%
		rename(mean_rsq = mean_test_score,
					 std_err = std_test_score)
	all_data_all_keras_scores = bind_rows(all_data_all_keras_scores, this_keras_scores)
}

write_csv(all_keras_scores, here('results/PRISM_LINCS_klaeger_models_auc/all_datasets/regression/keras/results/hyperparameter_search_metrics.csv'))
```

```{r}
#best metrics per feature count

all_data_best_keras_scores = data.frame()
for (feature_number in c(100,200,300,400,500,1000,1500,2000,3000,4000,5000)) {
	this_keras_scores = read_csv(
		here('results/PRISM_LINCS_klaeger_models_auc/all_datasets/regression/keras/results',
				 sprintf('hps_keras_%d.csv',feature_number))) %>% 
		mutate(num_features = feature_number) %>% 
		select(num_features, starts_with("param_"), mean_test_score, std_test_score) %>%
		rename(mean_rsq = mean_test_score,
					 std_err = std_test_score) %>% 
		arrange(desc(mean_rsq)) %>% 
		slice(1)
	
	all_data_best_keras_scores = bind_rows(all_data_best_keras_scores, this_keras_scores)
}

write_csv(best_keras_scores, here('results/PRISM_LINCS_klaeger_models_auc/all_datasets/regression/keras/results/best_hyperparameter_search_metrics.csv'))
```

```{r}
layers = c('one_layer', 'two_layer', 'four_layer', 'six_layer')

best_keras_scores = data.frame()
all_data_combined_all_keras_scores = data.frame()
all_data_combined_best_keras_scores = data.frame()	

for (feature_number in c(100,200,300,400,500,1000,1500,2000)) {

	for (layer in layers) {
		this_keras_scores = read_csv(
			here('results/PRISM_LINCS_klaeger_models_auc/all_datasets/regression/keras/results',layer,
					sprintf('%dfeat.csv',feature_number))) %>% 
			mutate(data_type = "all_datasets",
						 layers = paste0(layer))
			
	best_keras_scores = bind_rows(best_keras_scores, this_keras_scores)
	}

this_feature_scores = best_keras_scores %>%
	arrange(desc(mean_rsq)) %>% 
			slice(1)
	
all_data_combined_best_keras_scores = bind_rows(all_data_combined_best_keras_scores, this_feature_scores)
all_data_combined_all_keras_scores = bind_rows(all_data_combined_best_keras_scores, best_keras_scores) 

	
}

best_keras_scores = data.frame()
all_data_1500_all_keras_scores = data.frame()
all_data_1500_best_keras_scores = data.frame()
for (feature_number in c(1500)) {

	for (layer in layers) {
		this_keras_scores = read_csv(
			here('results/PRISM_LINCS_klaeger_models_auc/all_datasets/regression/keras/results',layer,
					sprintf('%dfeat.csv',feature_number))) %>% 
			mutate(data_type = "all_datasets",
						 layers = paste0(layer))
			
	best_keras_scores = bind_rows(best_keras_scores, this_keras_scores)
	}

this_feature_scores = best_keras_scores %>%
	arrange(desc(mean_rsq)) %>% 
			slice(1)
	
all_data_1500_best_keras_scores = bind_rows(all_data_1500_best_keras_scores, this_feature_scores)
all_data_1500_all_keras_scores = bind_rows(all_data_1500_all_keras_scores, best_keras_scores) 

	
}


all_data_combined_best_keras_scores = all_data_combined_best_keras_scores %>% 
	bind_rows(all_data_1500_best_keras_scores) %>% 
	unique() %>% 
	arrange(desc(mean_rsq))

write_csv(all_data_combined_all_keras_scores, here('results/PRISM_LINCS_klaeger_models_auc/all_datasets/regression/keras/results/hyperparameter_search_metrics.csv'))
write_csv(all_data_combined_best_keras_scores, here('results/PRISM_LINCS_klaeger_models_auc/all_datasets/regression/keras/results/best_hyperparameter_search_metrics.csv'))
```

Combine Inhibition Expression and All Datasets results

```{r}
all_combined_best_scores = combined_best_keras_scores %>% 
	bind_rows(all_data_combined_best_keras_scores)

all_combined_all_scores = combined_all_keras_scores %>% 
	bind_rows(all_data_combined_all_keras_scores)
```


```{r}
# best per feature plot
all_combined_best_scores %>%
	ggplot(aes(x = num_features, y = mean_rsq, colour = data_type, shape = data_type)) +
	geom_point() +
#  geom_errorbar(aes(ymin=mean-std_err, ymax=mean+std_err), width=.2,
#                position=position_dodge(.9)) +
	coord_cartesian(ylim= c(0.3,0.7)) +
	labs(title = "Keras Hyperparameter Search", x = "number of features", y = "R-squared") +
#	facet_wrap(vars(data_type)) +
		theme(
		legend.position = "top",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )

ggsave(here('figures/PRISM_LINCS_klaeger/keras_hyperparameter_search_metrics.png'), width = 10.5, height = 10.5, units = "cm")
```

```{r}
# all hyperparameter plot for best feature count
all_combined_all_scores %>%
	filter(num_features == combined_best_keras_scores$num_features[1]) %>% 
	mutate(
		layers = case_when(
		layers == "one_layer" ~ '1',
		layers == "two_layer" ~ '2', 
		layers == "four_layer" ~ '4',
		layers == "six_layer" ~ '6', 
		T ~ layers
					)
	) %>%
	mutate(layers = as.numeric(layers)) %>% 
	pivot_longer(c(dropout, neurons, layers), names_to = "hyperparameter", values_to = "value") %>% 
	ggplot(aes(x = value, y = mean_rsq)) +
	geom_point() +
#  geom_errorbar(aes(ymin=mean-std_err, ymax=mean+std_err), width=.2,
#                position=position_dodge(.9)) +
#	coord_cartesian(ylim= c(0.3,0.7)) +
	labs(title = "Keras Hyperparameter Search", x = "number of features", y = "R-squared") +
  facet_wrap(~hyperparameter, scales = "free_x") +
		theme(
		legend.position = "top",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )

ggsave(here('figures/PRISM_LINCS_klaeger/keras_hyperparameter_search_effects.png'), width = 10.5, height = 10.5, units = "cm")
```




