#Assess Model Predictions
```{r}
library(tidyverse)
library(patchwork)
library(here)
library(vroom)
library(cowplot)
```

```{r}
# Load the data
predictions <- vroom(here("results/PRISM_LINCS_klaeger_models_auc/final_model_predictions_xgboost.csv")) %>% 
	rename(predicted_auc = pred_auc)
sample_info <- vroom(here("data/CCLE_data/sample_info.csv")) %>%
  rename("depmap_id" = DepMap_ID) %>% 
	mutate(cell_line_name_extra = paste0(cell_line_name, "\n",lineage_subtype, "\n",lineage_sub_subtype))
LINCS_klaeger_data = read_csv(here('results/all_klaeger_LINCS_data_for_ml_long.csv'))
	# select(-binary_hit) %>% 
	# mutate(kinase = paste0("act_",kinase)) %>% 
	# pivot_wider(names_from = kinase, values_from = relative_intensity) %>% 
	# mutate_all(~replace(., is.na(.), 1))
```

```{r}
#generate promiscuity scores for drugs
promiscuity_scores = LINCS_klaeger_data %>% 
	group_by(drug) %>% 
	summarise(promiscuity_score = sum(binary_hit))

drug_targets = LINCS_klaeger_data %>%
	filter(binary_hit == 1) %>% 
	select(-relative_intensity)
	
drug_origins = LINCS_klaeger_data %>% 
	select(drug, origin) %>% 
	unique()
```

```{r}
# #add cell line info and promiscuity scores to predictions
full_predictions <- predictions %>%
  left_join(sample_info %>%
    select(
      depmap_id,
      primary_disease,
			cell_line_name_extra
    ),
  by = c("depmap_id")
  ) %>% 
	left_join(promiscuity_scores) %>% 
	left_join(drug_origins)

promiscuity_summary = full_predictions %>% 
	group_by(promiscuity_score) %>% 
	summarise(mean_predicted_auc = mean(predicted_auc)) 
	
promiscuity_summary %>%
	ggplot() +
	geom_point(aes(x = promiscuity_score, y = mean_predicted_auc))
```

```{r}
#In the 100 most kinase inhibitor sensitive cell lines within a given disease, which kinases are being targeted the most (kinase hit defined as >80% inhibition) 

primary_diseases = full_predictions %>%
	filter(!is.na(primary_disease)) %>% 
	pull(primary_disease) %>% 
	unique() 

top_10_kinases_per_disease = data.frame()
top_100_drugs_per_disease = data.frame()
for(disease in primary_diseases) {
	
	this_top_100_drugs = full_predictions %>% 
		filter(primary_disease == disease) %>% 
		group_by(primary_disease, drug) %>% 
		summarise(mean_predicted_auc = mean(predicted_auc)) %>% 
		arrange(mean_predicted_auc) %>% 
		mutate(disease_sub_rank = 1:n()) %>%
		filter(disease_sub_rank <= 100)
	
	this_top_100_drugs_with_target = this_top_100_drugs %>% 
		#join in drug target information
		left_join(drug_targets)
	
	this_kinase_scores = this_top_100_drugs_with_target %>% 
		select(primary_disease, kinase, binary_hit) %>% 
		group_by(primary_disease, kinase) %>%
		summarise(sensitivity_target_score = sum(binary_hit)) %>% 
		arrange(desc(sensitivity_target_score)) %>% 
		mutate(kinase_sub_rank = 1:n()) %>% 
		filter(kinase_sub_rank <= 10)
	
	top_100_drugs_per_disease = bind_rows(top_100_drugs_per_disease, this_top_100_drugs)
	top_10_kinases_per_disease = bind_rows(top_10_kinases_per_disease, this_kinase_scores)
	
}

kinase_order = top_10_kinases_per_disease %>%
	select(primary_disease, kinase) %>% 
	unique() %>% 
	count(kinase) %>% 
	arrange(n) %>% 
	mutate(kinase = fct_inorder(kinase))

top_10_kinases_per_disease$kinase = factor(top_10_kinases_per_disease$kinase, levels = kinase_order$kinase)

top_10_kinases_per_disease %>% 
	ggplot(aes(x = primary_disease, y = kinase, size = sensitivity_target_score, colour = kinase)) +
	geom_point(alpha = 0.7) +
	labs(x = " ", y = "Kinase", title = "Kinase Importance by Cancer Type", size = "Cell Lines Sensitive to the Given Kinase") +
		theme(
		legend.position = "bottom",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      ) +
	scale_color_discrete(guide = "none") 

ggsave(here('figures/PRISM_LINCS_klaeger/keras_predictions_top_kinase_targets_per_disease_auc.png'), width = 8, height = 6)

drug_order = top_100_drugs_per_disease %>%
	select(primary_disease, drug) %>% 
	unique() %>% 
	count(drug) %>% 
	arrange(n) %>% 
	mutate(drug = fct_inorder(drug))

top_100_drugs_per_disease$drug = factor(top_100_drugs_per_disease$drug, levels = drug_order$drug)

top_100_drugs_per_disease %>% 
	ggplot(aes(x = primary_disease, y = drug, fill = mean_predicted_auc)) +
	geom_tile() +
	labs(x = " ", y = "Kinase", title = "Kinase Importance by Cancer Type", size = "Cell Lines Sensitive to the Given Kinase") +
		theme(
		legend.position = "bottom",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      ) +
	scale_fill_gradient2(trans = "reverse")

ggsave(here('figures/PRISM_LINCS_klaeger/keras_predictions_top_kinase_targets_per_disease_auc.png'), width = 8, height = 6)
```


```{r}
# BC cell lines

bc_cell_lines = sample_info %>% 
	filter(cell_line_name %in% c("SK-BR-3","MCF7","MDA-MB-436","HCC1806",
															 "MDA-MB-231","BT-474","SUM-149PT","SUM-159PT",
															 "SUM-229PE"))
```

```{r}
# Pull out interesting predictions

BC_predictions = full_predictions  %>%
	filter(depmap_id %in% bc_cell_lines$depmap_id)
	
```

```{r}
get_interesting_pred_plots <- function(this_cell_line_name = "BT474", these_prediction_results = BC_predictions) {
	
	
#### Get Kinobeads Plots	#####################################################################################
# 	these_predictions = these_prediction_results %>% 
# 		filter(stripped_cell_line_name == this_cell_line_name) %>% 
# 		filter(origin == "Kinobeads")
# 	
# 	these_summary = these_predictions %>%
# 		group_by(drug) %>%
# 		summarise(predicted_auc = predicted_auc, 
# 							null_prox = abs(mean(predicted_auc - 1))) %>%
# 		arrange(predicted_auc)
# 	
# 	line_name_extended = unique(these_predictions$cell_line_name_extra)
# 
# 	deadly_pred_set = these_predictions %>%
# 		mutate(drug = fct_relevel(drug,as.character(these_summary$drug))) %>%
# 		filter(drug %in% these_summary$drug[1:10]) %>% 
# 		mutate(effect = "High Effect")
# 	
# 	null_sort = these_summary %>%
# 		arrange(null_prox)
# 	
# 	null_eff_set = these_predictions %>%
# 		mutate(drug = fct_relevel(drug,as.character(null_sort$drug))) %>%
# 		filter(drug %in% null_sort$drug[1:10]) %>% 
# 		mutate(effect = "Low Effect")
# 	
# 	combined_set = bind_rows(deadly_pred_set, null_eff_set)
# 	
# 	high_eff_plot = ggplot(deadly_pred_set, aes(x=drug, y=predicted_auc)) +
# 		geom_col() +
# 		geom_line() + 
# 		labs(x="Drug", 
# 				 y="Predicted auc") +
# 		coord_cartesian(y = c(0.4,1)) +
# 		theme(
# 		legend.position = "bottom",
# 		legend.text = element_text(size = 9),
# 		legend.background = element_rect(fill = "transparent",colour = NA),
# 		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
# 		panel.background = element_rect(fill = "transparent",colour = NA),
#     panel.grid.minor = element_blank(),
#     panel.grid.major = element_blank(),
#     plot.background = element_rect(fill = "transparent",colour = NA)
#       ) +
# 		scale_fill_discrete(guide = "none") +
# 		facet_wrap(vars(effect, origin))
# 	
# 		null_eff_plot = ggplot(null_eff_set, aes(x=drug, y=predicted_auc)) +
# 		geom_col() +
# 		geom_line() + 
# 		labs(x="Drug", 
# 				 y="Predicted auc") +
# 		coord_cartesian(y = c(0,1)) +
# 		theme(
# 		legend.position = "bottom",
# 		legend.text = element_text(size = 9),
# 		legend.background = element_rect(fill = "transparent",colour = NA),
# 		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
# 		panel.background = element_rect(fill = "transparent",colour = NA),
#     panel.grid.minor = element_blank(),
#     panel.grid.major = element_blank(),
#     plot.background = element_rect(fill = "transparent",colour = NA)
#       ) +
# 		scale_fill_discrete(guide = "none") +
# 		facet_wrap(vars(effect, origin))
# 	
# 	
# full_kinobeads_plot = plot_grid(high_eff_plot, null_eff_plot)

#### Get KINOMEscan Plots	#####################################################################################

	these_predictions = these_prediction_results %>% 
		filter(stripped_cell_line_name == this_cell_line_name) %>% 
		filter(origin == "KINOMEscan")
	
	these_summary = these_predictions %>%
		group_by(drug) %>%
		summarise(predicted_auc = predicted_auc, 
							null_prox = abs(mean(predicted_auc - 1))) %>%
		arrange(predicted_auc)
	
	line_name_extended = unique(these_predictions$cell_line_name_extra)

	deadly_pred_set = these_predictions %>%
		mutate(drug = fct_relevel(drug,as.character(these_summary$drug))) %>%
		filter(drug %in% these_summary$drug[1:20]) %>% 
		mutate(effect = "High Effect")
	
	null_sort = these_summary %>%
		arrange(null_prox)
	
	null_eff_set = these_predictions %>%
		mutate(drug = fct_relevel(drug,as.character(null_sort$drug))) %>%
		filter(drug %in% null_sort$drug[1:20]) %>% 
		mutate(effect = "Low Effect")
	
	combined_set = bind_rows(deadly_pred_set, null_eff_set)
	
	high_eff_plot = ggplot(deadly_pred_set, aes(x=drug, y=predicted_auc)) +
		geom_col() +
		geom_line() + 
		labs(x="Drug", 
				 y="Predicted auc") +
		coord_cartesian(y = c(0.4,1)) +
		theme(
		legend.position = "bottom",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      ) +
		scale_fill_discrete(guide = "none") +
		facet_wrap(vars(effect, origin))
	
		null_eff_plot = ggplot(null_eff_set, aes(x=drug, y=predicted_auc)) +
		geom_col() +
		geom_line() + 
		labs(x="Drug", 
				 y="Predicted auc") +
		coord_cartesian(y = c(0.4,1)) +
		theme(
		legend.position = "bottom",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      ) +
		scale_fill_discrete(guide = "none") +
		facet_wrap(vars(effect, origin))
	
	
full_kinomescan_plot = plot_grid(high_eff_plot , null_eff_plot) 

#### Get Overlap Plots	#####################################################################################
# 
# 	these_predictions = these_prediction_results %>% 
# 		filter(stripped_cell_line_name == this_cell_line_name) %>% 
# 		filter(origin == "overlap")
# 	
# 	these_summary = these_predictions %>%
# 		group_by(drug) %>%
# 		summarise(predicted_auc = predicted_auc, 
# 							null_prox = abs(mean(predicted_auc - 1))) %>%
# 		arrange(predicted_auc)
# 	
# 	line_name_extended = unique(these_predictions$cell_line_name_extra)
# 
# 	deadly_pred_set = these_predictions %>%
# 		mutate(drug = fct_relevel(drug,as.character(these_summary$drug))) %>%
# 		filter(drug %in% these_summary$drug[1:10]) %>% 
# 		mutate(effect = "High Effect")
# 	
# 	null_sort = these_summary %>%
# 		arrange(null_prox)
# 	
# 	null_eff_set = these_predictions %>%
# 		mutate(drug = fct_relevel(drug,as.character(null_sort$drug))) %>%
# 		filter(drug %in% null_sort$drug[1:10]) %>% 
# 		mutate(effect = "Low Effect")
# 	
# 	combined_set = bind_rows(deadly_pred_set, null_eff_set)
# 	
# 	high_eff_plot = ggplot(deadly_pred_set, aes(x=drug, y=predicted_auc)) +
# 		geom_col() +
# 		geom_line() + 
# 		labs(x="Drug", 
# 				 y="Predicted auc") +
# 		coord_cartesian(y = c(0.4,1)) +
# 		theme(
# 		legend.position = "bottom",
# 		legend.text = element_text(size = 9),
# 		legend.background = element_rect(fill = "transparent",colour = NA),
# 		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
# 		panel.background = element_rect(fill = "transparent",colour = NA),
#     panel.grid.minor = element_blank(),
#     panel.grid.major = element_blank(),
#     plot.background = element_rect(fill = "transparent",colour = NA)
#       ) +
# 		scale_fill_discrete(guide = "none") +
# 		facet_wrap(vars(effect, origin))
# 	
# 		null_eff_plot = ggplot(null_eff_set, aes(x=drug, y=predicted_auc)) +
# 		geom_col() +
# 		geom_line() + 
# 		labs(x="Drug", 
# 				 y="Predicted auc") +
# 		coord_cartesian(y = c(0.5,1)) +
# 		theme(
# 		legend.position = "bottom",
# 		legend.text = element_text(size = 9),
# 		legend.background = element_rect(fill = "transparent",colour = NA),
# 		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
# 		panel.background = element_rect(fill = "transparent",colour = NA),
#     panel.grid.minor = element_blank(),
#     panel.grid.major = element_blank(),
#     plot.background = element_rect(fill = "transparent",colour = NA)
#       ) +
# 		scale_fill_discrete(guide = "none") +
# 		facet_wrap(vars(effect, origin))
# 	
# 	
# full_overlap_plot = plot_grid(high_eff_plot, null_eff_plot) 

full_plot = plot_grid(full_kinomescan_plot) 

full_final_plot = full_plot + plot_annotation(title = "Model Predictions", subtitle = paste0(line_name_extended))

return(full_plot)
}

dir.create(here('figures/PRISM_LINCS_klaeger/final_xgboost_model//BC_lines_predictions/'), showWarnings = F)
for (this_line in unique(BC_predictions$stripped_cell_line_name)) {
	this_plot = get_interesting_pred_plots(this_line)
	ggsave(here('figures/PRISM_LINCS_klaeger/final_xgboost_model//BC_lines_predictions/',paste0(this_line,".png")), this_plot, width=16,height=5)
}
```