---
title: "prep PRISM LINCS klaeger data with all other datasets"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(vroom)
```

```{r}
#read in data 
compound_match_list = read_csv(here('results/matching/LINCS_PRISM_klaeger_combined_drug_matches_final.csv'))

LINCS_klaeger_data_wide = read_csv(here('results/all_klaeger_LINCS_data_for_ml_wide.csv'))

PRISM_ic50 = read_csv(here('results/PRISM_LINCS_klaeger_models_ic50/PRISM_ic50_for_ml.csv'))

CCLE = read_rds(here('data/full_CCLE_expression_set_for_ML.rds')) %>% 
	rename('depmap_id' = DepMap_ID) %>% 
	filter(depmap_id %in% PRISM_ic50$depmap_id)

CNV = read_rds(here('data/full_CCLE_CNV_set_for_ML.rds'))

proteomics_data = vroom(here('data/CCLE_proteomics_imputed_wide.csv.gz')) %>%
	select(-CCLE_cell_line_name,-tenplex_number) %>% 
	rename_with( ~ paste0("prot_", .x), -DepMap_ID)

depmap_data = read_rds(here('data/full_depmap_for_ML.rds'))
```

```{r}
#prefering klaeger names for matching
compound_match_list_processed = compound_match_list %>% 
	mutate(drug = if_else(is.na(klaeger_name), 
												LINCS_name, 
												klaeger_name)) %>% 
	select(drug, broad_id) %>% 
	unique()

duplicate_broad_ids = compound_match_list_processed %>% 
	count(drug)
```

```{r}
#variable renaming
CCLE_processed = CCLE %>% 
	rename_with(~ str_replace(.x, "[-;]", "_"))

CNV_processed = CNV %>% 
 rename_with(~ str_replace(.x, "[-;]", "_"))

proteomics_data_processed = proteomics_data %>% 
	rename_with(~ str_replace(.x, "[-;]", "_"))

depmap_data_processed = depmap_data %>% 
	rename_with(~ str_replace(.x, "[-;]", "_"))

```

```{r}
PRISM_ic50_binarized = PRISM_ic50 %>% 
	mutate(ic50_binary = if_else(
		ic50 <= median(PRISM_ic50$ic50),
		1,
		0
	))

LINCS_klaeger_data_for_model = LINCS_klaeger_data_wide %>% 
	left_join(compound_match_list_processed) %>% 
	filter(!is.na(broad_id))

all_model_data = PRISM_ic50_binarized %>% 
	filter(depmap_id %in% depmap_data_processed$DepMap_ID) %>%
	filter(depmap_id %in% CCLE_processed$depmap_id) %>%
	filter(depmap_id %in% CNV_processed$DepMap_ID) %>%
	filter(depmap_id %in% proteomics_data_processed$DepMap_ID) %>%
	left_join(CCLE_processed, by = 'depmap_id') %>% 
	left_join(LINCS_klaeger_data_for_model, by = c('broad_id')) %>% 
	mutate(ic50_binary = as.factor(ic50_binary)) %>%
	left_join(depmap_data_processed, by=c('depmap_id' = 'DepMap_ID')) %>%
	left_join(CNV_processed, by=c('depmap_id' = 'DepMap_ID')) %>%
	left_join(proteomics_data_processed, by=c('depmap_id' = 'DepMap_ID')) %>%
	drop_na()

#excluding ic50 values below 1 nM and over 30 uM
all_data_filtered = all_model_data %>% 
	filter(ic50 <= 30 & ic50 >= 0.001) %>% 
	mutate(across(starts_with(c('ic50_binary')), ~ as.factor(.)))

all_data_filtered %>% 
	ggplot(aes(x = log(ic50))) +
	geom_histogram()

#Need a log transform

all_data_filtered_transformed = all_data_filtered %>% 
	mutate(ic50 = log(ic50))

all_data_filtered_transformed %>% 
	ggplot(aes(x = ic50)) +
	geom_histogram()

write_rds(all_data_filtered_transformed, here('results/PRISM_LINCS_klaeger_models_ic50/PRISM_LINCS_klaeger_all_multiomic_data_for_ml_ic50.rds.gz'), compress = "gz")
```

