```{r}
library(tidyverse)
library(patchwork)
library(here)
library(vroom)
library(ggdendro)
```

```{r}
# Load the data
cardio_toxicity_data = read_csv(here('data/cardio_toxicity_data.csv')) %>% 
	rename(drug = Drug)
LINCS_klaeger_data = read_csv(here('results/all_klaeger_LINCS_data_for_ml_long.csv'))
cardio_toxicity_data_full = read_rds(here('results/cardio_toxicity_models/cardio_toxicity_data_for_ml.rds.gz'))
```

```{r}
#pre-process data
cardio_toxicity_data_processed = cardio_toxicity_data %>% 
	mutate(across(-drug, ~case_when(. == 0 ~ "No Reported Event",
																	. == 1 ~ "Reported Event",
																	. == 2 ~ ">10% Incidence"))) 

cardio_toxicity_data_long = cardio_toxicity_data_processed %>% 
	pivot_longer(-drug, names_to = "cardiac_adverse_event", values_to = "Incidence")

cardio_toxicity_data_full_long = cardio_toxicity_data_full %>% 
	pivot_longer(starts_with("act_"), names_to = "kinase", values_to = "relative_intensity") %>% 
	separate(kinase, into = c('prefix', 'kinase'), sep = "_") %>% 
	select(-prefix)
	
```

```{r}
#generate promiscuity scores for drugs
promiscuity_scores = LINCS_klaeger_data %>% 
	group_by(drug) %>% 
	summarise(promiscuity_score = sum(binary_hit))

drug_targets = LINCS_klaeger_data %>%
	filter(binary_hit == 1) %>% 
	select(-relative_intensity)
```

```{r}
#plot by promiscuity 

cardio_promiscuity_data = cardio_toxicity_data_long %>% 
	left_join(promiscuity_scores) %>% 
	mutate(Incidence = as.factor(Incidence)) %>% 
	mutate(Incidence = fct_relevel(Incidence, "No Reported Event", "Reported Event", ">10% Incidence"))

cardio_promiscuity_data %>% 
	ggplot(aes(x = Incidence, y = promiscuity_score, fill = Incidence)) +
	geom_violin() +
	facet_wrap(~cardiac_adverse_event) +
	labs(y = "Inhibitor Promiscuity", title = "Inhibitor Promiscuity Does Not Explain Cardiac Toxicity") +
		theme(
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )
ggsave(here('figures/cardio_toxicity/promscuity_by_event_figure.png'), height = 10.5, width = 21, units = "cm")
```

```{r}
#plot by top targets 

primary_diseases = cardio_promiscuity_data %>%
	filter(!is.na(cardiac_adverse_event)) %>% 
	pull(cardiac_adverse_event) %>% 
	unique() 

top_10_drugs_per_disease = data.frame()
top_10_kinases_per_disease = data.frame()
for(disease in primary_diseases) {
	
	this_top_10_drugs = cardio_promiscuity_data %>% 
		filter(cardiac_adverse_event == disease) %>%
		mutate(Incidence_score =  case_when(
																	Incidence == "No Reported Event" ~ 0,
																	Incidence == "Reported Event" ~ 1,
																	Incidence == ">10% Incidence" ~ 2)) %>%
		group_by(cardiac_adverse_event, drug) %>% 
		summarise(mean_Incidence_score = mean(Incidence_score)) %>% 
		arrange(mean_Incidence_score) %>% 
		mutate(disease_sub_rank = 1:n()) %>%
		filter(disease_sub_rank <= 10)
	
	this_top_10_drugs_with_target = this_top_10_drugs %>% 
		#join in drug target information
		left_join(drug_targets)
	
	this_kinase_scores = this_top_10_drugs_with_target %>% 
		select(cardiac_adverse_event, kinase, binary_hit) %>% 
		group_by(cardiac_adverse_event, kinase) %>%
		summarise(target_score = sum(binary_hit)) %>% 
		arrange(desc(target_score)) %>% 
		mutate(kinase_sub_rank = 1:n()) %>% 
		filter(kinase_sub_rank <= 10)
	
	top_10_drugs_per_disease = bind_rows(top_10_drugs_per_disease, this_top_10_drugs)
	top_10_kinases_per_disease = bind_rows(top_10_kinases_per_disease, this_kinase_scores)
	
}

kinase_order = top_10_kinases_per_disease %>%
	select(cardiac_adverse_event, kinase) %>% 
	unique() %>% 
	count(kinase) %>% 
	arrange(n) %>% 
	mutate(kinase = fct_inorder(kinase))

top_10_kinases_per_disease$kinase = factor(top_10_kinases_per_disease$kinase, levels = kinase_order$kinase)

top_10_kinases_per_disease %>% 
	ggplot(aes(x = cardiac_adverse_event, y = kinase, size = target_score, colour = kinase)) +
	geom_point(alpha = 0.7) +
	labs(x = " ", y = "Kinase", title = "Kinase Inhibition Frequency\nby Cardiac Toxicity", size = "Number of Toxicity-Causing Drugs\nThat Inhibit the Given Kinase") +
		theme(
		legend.position = "bottom",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      ) +
	guides(size = guide_legend(title.position = "bottom",
														 title.hjust = 0.5)) +
	scale_color_discrete(guide = "none")

ggsave(here('figures/cardio_toxicity/kinase_inhibition_by_event_figure.png'), height = 20, width = 10, units = "cm")
```

```{r}
#drug heirarchichal clustering

#scaling columns
matrix_scaled <- cardio_toxicity_data
matrix_scaled[, c(2:7)] <- scale(matrix_scaled[, 2:7])

#clustering
cluster_matrix <- as.matrix(matrix_scaled[, -c(1)])
rownames(cluster_matrix) <- matrix_scaled$drug
matrix_dendro <- as.dendrogram(hclust(d = dist(x = cluster_matrix)))

# Create dendro
dendro_plot <- ggdendrogram(data = matrix_dendro, rotate = TRUE)

#drug heirarchichal clustering

#scaling columns
matrix_scaled <- cardio_toxicity_data
matrix_scaled[, c(2:7)] <- scale(matrix_scaled[, 2:7])

#clustering
cluster_matrix <- as.matrix(matrix_scaled[, -c(1)])
rownames(cluster_matrix) <- matrix_scaled$drug
matrix_dendro <- as.dendrogram(hclust(d = dist(x = cluster_matrix)))

# Create dendro
dendro_plot <- ggdendrogram(data = matrix_dendro, rotate = TRUE)
ggsave(here('figures/cardio_toxicity/dendro_plot.png'))

#heatmap plot
drug_order <- order.dendrogram(matrix_dendro)
cardio_toxicity_data_long$drug <- factor(x = cardio_toxicity_data_long$drug,
                               levels = matrix_scaled$drug[drug_order], 
                               ordered = TRUE)

cardio_toxicity_data_full_long$drug <- factor(x = cardio_toxicity_data_full_long$drug,
                               levels = matrix_scaled$drug[drug_order], 
                               ordered = TRUE)

event_heatmap_plot = cardio_toxicity_data_long %>% 
	ggplot(aes(x = cardiac_adverse_event, y = drug)) +
	labs(y = "Clinical Kinase Inhibitors") +
  geom_tile(aes(fill = Incidence)) +
  scale_fill_viridis_d() +
  theme(
  	legend.position = "bottom",
  	legend.direction = "vertical",
  	axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
  	axis.title.x = element_blank(),
  	axis.text.y = element_blank(),
    axis.ticks.y = element_blank())

ggsave(here('figures/cardio_toxicity/event_heatmap.png'), width = 4, height = 21, units = "cm")

target_heatmap_plot = cardio_toxicity_data_full_long %>%
	ggplot(aes(x = kinase, y = drug)) +
	labs(x = "Kinase") +
  geom_tile(aes(fill = relative_intensity)) +
  scale_fill_viridis_c() +
  theme(
  	legend.position = "bottom",
  	axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
  	axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
  	axis.title.y = element_blank(),
  	axis.text.y = element_blank())

ggsave(here('figures/cardio_toxicity/target_heatmap.png'), width = 21, height = 18.93, units = "cm")
```


