---
title: "prep PRISM LINCS klaeger data"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
```

```{r}
#read in data 
cardio_toxicity_data = read_csv(here('data/cardio_toxicity_data.csv'))
LINCS_klaeger_data_long = read_csv(here('results/all_klaeger_LINCS_data_for_ml_long.csv'))
```

```{r}
#variable renaming
LINCS_klaeger_data_long_processed = LINCS_klaeger_data_long %>% 
	mutate(kinase = str_replace(kinase, "[-;]", "_")) %>% 
	mutate(kinase = if_else(
		kinase == 'HIST2H2BE_HIST1H2BB;HIST1H2BO;HIST1H2BJ;HIST3H2BB;HIST1H2BA',
		'HIST2H2BE_HIST1H2BB_HIST1H2BO_HIST1H2BJ_HIST3H2BB_HIST1H2BA',
		kinase
	))

cardio_toxicity_data_processed = cardio_toxicity_data %>% 
	mutate(across(-Drug, ~as.factor(.))) %>% 
	rename(drug = Drug)
```


```{r}
LINCS_klaeger_data_for_model = LINCS_klaeger_data_long_processed %>% 
	mutate(act_gene_name = paste0('act_', kinase)) %>% 
	select(-kinase, -binary_hit) %>%  
	pivot_wider(names_from = act_gene_name, values_from = relative_intensity) %>% 
	mutate_all(~replace(., is.na(.), 1)) 

all_model_data = cardio_toxicity_data_processed %>% 
	left_join(LINCS_klaeger_data_for_model) %>% 
	drop_na() 

LINCS_klaeger_data_for_model_binary_hit = LINCS_klaeger_data_long_processed %>% 
	mutate(act_gene_name = paste0('act_', kinase)) %>% 
	select(-kinase, -relative_intensity) %>% 
	pivot_wider(names_from = act_gene_name, values_from = binary_hit) %>% 
	mutate_all(~replace(., is.na(.), 1)) 

all_binary_model_data = cardio_toxicity_data_processed %>% 
	left_join(LINCS_klaeger_data_for_model_binary_hit) %>% 
	drop_na()

write_rds(all_model_data,
					here('results/cardio_toxicity_models/cardio_toxicity_data_for_ml.rds.gz'), compress = "gz")
write_rds(all_binary_model_data, 
					here('results/cardio_toxicity_models/cardio_toxicity_data_for_ml_binary.rds.gz'), compress = "gz")

```